from manim import *
from math import sqrt

class AMGM(Scene):
    def construct(self):
        title = Tex(r"The AM-GM inequality for two variables")
        self.play(Write(title))
        self.wait()
        title2 = Tex(r"We will show: $\sqrt{ab} \leq \frac{a + b}{2}$ ").move_to(DOWN)
        self.play(Write(title2))
        self.wait(2)
        self.play(FadeOut(title), FadeOut(title2), run_time=0.5)
        self.wait()
        circle = Circle(radius=2)
        diam = Line([-2, 0, 0], [2, 0, 0], color=BLUE)
        texta = MathTex(r"a").move_to(0.25*DOWN + 0.5*RIGHT)
        texta.font_size=40
        textb = MathTex(r"b").move_to(0.25*DOWN + 1.5*LEFT)
        textb.font_size=40
        texte = MathTex(r"e").move_to((sqrt(3)/2)*UP + 0.75*LEFT)
        texte.font_size=40
        line1 = Line([-1, 0, 0], [-1, sqrt(3), 0], color=BLUE)
        self.play(  Create(circle), Create(diam),
                    Write(texta), Write(textb), Write(texte), 
                    Create(line1))  
        self.wait(1)  
        line2 = Line([-1, sqrt(3), 0], [-2, 0, 0], color=BLUE)
        line3 = Line([-1, sqrt(3), 0], [2, 0, 0], color=BLUE)
        self.play(Create(line2), Create(line3))
        self.wait()
        textc = MathTex(r"c").move_to(1*UP + 1.6*LEFT)
        textc.font_size=40
        textd = MathTex(r"d").move_to(1.1*UP + 0.5*RIGHT)
        textd.font_size=40
        self.play(Create(textc), Create(textd))
        self.wait()
        rightangle1 = RightAngle(line1, diam, length=0.25)
        rightangle2 = RightAngle(line1, diam, length=0.25, quadrant=(1,-1))
        rightangle3 = RightAngle(line2, line3, length=0.25)
        self.play(Create(rightangle1), Create(rightangle2), Create(rightangle3))
        self.wait()
        group = VGroup( circle, diam, texta, textb, texte, line1,
                        line2, line3, textc, textd, rightangle1,
                        rightangle2, rightangle3)
        self.play(group.animate.shift(1.9*UP))
        self.wait()
        maths1 = MathTex(r"(a + b)^2 = c^2 + d^2").move_to(DOWN)
        self.play(Write(maths1))
        self.wait()
        maths2 = MathTex(r"a^2 + e^2 = c^2 \ \text{and}\  b^2 + e^2 = d^2")
        maths2.move_to(2*DOWN)
        self.play(Write(maths2))
        self.wait()
        maths3 = MathTex(r"\Longrightarrow (a + b)^2 = a^2 + e^2 + b^2 + e^2")
        maths3.move_to(3*DOWN)
        self.play(Write(maths3))
        self.wait()
        self.play(Unwrite(maths1), Unwrite(maths2), run_time=0.5)
        self.play(maths3.animate.shift(2*UP))
        self.wait()
        maths4 = MathTex(r"(a + b)^2 = a^2 + b^2 + 2e^2").move_to(DOWN)
        self.play(Transform(maths3, maths4))
        self.wait()
        maths5 = MathTex(r"a^2 + 2ab + b^2 = a^2 + b^2 + 2e^2").move_to(DOWN)
        self.play(Transform(maths3, maths5))
        self.wait()
        maths6 = MathTex(r"ab = e^2").move_to(DOWN)
        self.play(Transform(maths3, maths6))
        self.wait()
        maths7 = MathTex(r"\sqrt{ab} = e").move_to(DOWN)
        self.play(Transform(maths3, maths7))
        self.wait()
        maths8 = Tex(r"$e$ is at most the radius, hence").move_to(2*DOWN)
        self.play(Write(maths8))
        self.wait()
        maths9 = MathTex(r"\sqrt{ab} \leq \frac{a + b}{2}").move_to(3*DOWN)
        self.play(Write(maths9))
        self.wait()
        self.play(FadeOut(maths3, maths8, maths9))
        self.play(group.animate.shift(1.9*DOWN))
        self.play(  FadeOut(texta, textb, textc, textd, texte,
                    rightangle1, rightangle2, rightangle3))
        text8 = Tex("Animated by Adil Raza").move_to(3*DOWN)
        self.play(Write(text8), run_time = 2)
        self.wait(4)
