from manim import *


class Scene(Scene):
    def construct(self):
        title = Tex(r"Area of a parallelogram = Base $\times$ Height")
        self.play(Write(title))
        self.wait(1)
        self.play(title.animate.to_corner(UP))
        self.wait()
        points = [[-4, -2, 0], [-2, 2, 0], [4, 2, 0], [2, -2, 0]]
        parallelogram = Polygon(*points, stroke_color=YELLOW)
        self.play(Create(parallelogram))
        self.wait()
        self.play(FadeOut(title), run_time = 1)
        line1 = Line([-2, -2, 0], [-2, 2, 0], color = BLUE)
        self.play(Create(line1))
        self.wait()
        line2 = Line([-4, -2, 0], [-2, -2, 0], color = BLUE)
        rightangle = RightAngle(line1, line2, quadrant=(1,-1), color = BLUE)
        self.play(Create(rightangle))
        self.wait()
        text = Tex(r"Height").move_to(1*LEFT)
        text1 = Tex(r"Base").move_to(2.5*DOWN + 1*LEFT)
        self.play(Write(text), Write(text1))
        line3 = Line([-4, -2, 0], [-2, 2, 0], color = BLUE)
        group = VGroup(line1, line2, line3, rightangle)
        points2 = [[-3, -2, 0], [-3, 2, 0], [3, 2, 0], [3, -2, 0]]
        rectangle = Polygon(*points2, stroke_color=YELLOW)
        self.play(FadeIn(line2, line3))
        self.wait()
        line1copy = Line([-2, -2, 0], [-2, 2, 0], color = YELLOW)
        self.play(  FadeIn(line1copy),
                    group.animate.shift(6*RIGHT),
                    text.animate.shift(6*RIGHT))
        self.wait()
        linea = Line([-2, 2, 0], [4, 2, 0], color = YELLOW)
        linec = Line([-2, -2, 0], [2, -2, 0], color = YELLOW)
        group1 = VGroup(linea, linec)
        group2 = VGroup(group1, group, text, line1copy)
        self.play(  FadeIn(group1),
                    FadeOut(parallelogram))
        self.play(group2.animate.shift(1*LEFT), text1.animate.shift(1*RIGHT))
        self.wait()
        textarea = Tex(r"Area =").move_to(3*DOWN + 2*LEFT)
        self.play(Write(textarea))
        self.wait()
        texta = text1.copy()
        transform_texta = Tex(r"Base").move_to(3.005*DOWN + 0.5*LEFT)
        self.play(Transform(texta, transform_texta))
        self.wait()
        times = MathTex(r"\times").move_to(3.05*DOWN + 0.25*RIGHT)
        self.play(FadeIn(times), run_time = 0.1)
        self.wait()
        textb = text.copy()
        transform_textb = Tex(r"Height").move_to(3.05*DOWN + 1.25*RIGHT)
        self.play(Transform(textb, transform_textb))
        self.wait(4)
        self.play(FadeOut(text, text1, times, textb, texta, textarea))
        text8 = Tex("Animated by Adil Raza").move_to(3*DOWN)
        self.play(Write(text8), run_time = 2)
        self.wait(4)
